// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250825143046_AddSeoKeywordsToTopicBlog")]
    partial class AddSeoKeywordsToTopicBlog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_blogs");

                    b.HasAlternateKey("Slug")
                        .HasName("ak_blogs_slug");

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_blogs_username");

                    b.ToTable("blogs", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ProductBlog", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("integer")
                        .HasColumnName("blog_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<string>("KeySellingPoints")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_selling_points");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_type");

                    b.Property<string>("SeoKeywords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_keywords");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("size");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_audience");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("volume");

                    b.HasKey("BlogId")
                        .HasName("pk_productblogs");

                    b.ToTable("productblogs", (string)null);
                });

            modelBuilder.Entity("Backend.Models.TopicBlog", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("integer")
                        .HasColumnName("blog_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("KeySellingPoints")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_selling_points");

                    b.Property<string>("SeoKeywords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_keywords");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_audience");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("BlogId")
                        .HasName("pk_topicblogs");

                    b.ToTable("topicblogs", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("Username")
                        .HasName("ak_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Blog", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("Username")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blogs_users_username");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.ProductBlog", b =>
                {
                    b.HasOne("Backend.Models.Blog", "Blog")
                        .WithOne("ProductBlog")
                        .HasForeignKey("Backend.Models.ProductBlog", "BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productblogs_blogs_blog_id");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Backend.Models.TopicBlog", b =>
                {
                    b.HasOne("Backend.Models.Blog", "Blog")
                        .WithOne("TopicBlog")
                        .HasForeignKey("Backend.Models.TopicBlog", "BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topicblogs_blogs_blog_id");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Backend.Models.Blog", b =>
                {
                    b.Navigation("ProductBlog");

                    b.Navigation("TopicBlog");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
