export const globalSeoKeywords = [
  // Theo mục đích sử dụng
  "thang máy hành khách",
  "thang máy dân dụng",
  "thang máy văn phòng",
  "thang máy trường học",
  "thang máy bệnh viện",
  "thang máy nhà phố",
  "thang máy chung cư mini",
  "thang máy công trình công",
  "thang máy cho trung tâm y tế",
  "thang máy cho cơ quan nhà nước",
  "thang máy gia đình",
  "thang máy cho biệt thự",
  "thang máy cho người già",
  "thang máy cho khách sạn",
  "thang máy sân khấu, nhà hát",
  "thang máy cho xưởng sản xuất",
  // Theo đặc điểm kỹ thuật
  "thang máy không phòng máy",
  "thang máy không hố pit",
  "thang máy tải trọng 450kg",
  "thang máy tải trọng 630kg",
  "thang máy tải trọng 1000kg",
  "thang máy tốc độ cao",
  "thang máy trục vít",
  "thang máy thủy lực",
  "thang máy có phòng máy",
  "thang máy nhập khẩu nguyên chiếc",
  "thang máy liên doanh",
  "thang máy Mitsubishi",
  "thang máy Hitachi",
  "thang máy Fuji",
  "thang máy Sanyo",
  "thang máy cáp kéo",
  "thang máy lồng kính",
  "thang máy quan sát",
  "thang máy mini tiết kiệm diện tích",
  "thang máy vận hành bằng tời trục vít",
  "thang máy chống cháy",
  "thang máy 1:1",
  "thang máy 2:1",
  "thang máy tải trọng 250kg",
  "thang máy tải trọng 750kg",
  "thang máy tải trọng 1.500kg",
  "thang máy chở hàng kiêm hành khách",
  "thang máy chuyên dụng cho nhà xe",
  // Theo thương hiệu
  "thang máy Schindler",
  "thang máy ThyssenKrupp",
  "thang máy Otis",
  "thang máy Cibes",
  "thang máy nhập khẩu Châu Âu",
  "thang máy liên doanh Việt – Nhật",
  // Một số cụm từ tìm kiếm phổ biến
  "giá thang máy gia đình trọn gói",
  "thủ tục xin phép lắp thang máy nhà ở",
  "mua thang máy cho khách sạn nhỏ ở đâu uy tín",
  "thang máy lồng kính cho nhà phố hẹp",
  "bảo trì thang máy gia đình định kỳ bao lâu",
  "thang máy an toàn cho người già và trẻ em",
  "ưu điểm thang máy không phòng máy so với có phòng máy",
  "thang máy tải hàng kết hợp tải người",
  "bảng giá thang máy nhập khẩu nguyên chiếc",
  "những lưu ý khi cải tạo nhà lắp thang máy",
] as const;
